name: Automated Bandit Tests

on:
  push:
    paths:
      - 'try.py'

jobs:
  bandit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.0

    - name: Install Bandit
      run: |
        python -m pip install --upgrade pip
        pip install bandit

    - name: Run Bandit tests
      run: bandit -r .

    - name: Commit and push changes if tests pass
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .
        git diff --quiet && git diff --staged --quiet || git commit -m "Automated commit: Bandit scan passed"
        git push origin main
