name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Define the branch where you want to trigger this workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: docker build -t pd-chatbot:v0 .
      working-directory: dev/Dockerfile.dev
    - name: Push Docker Image
      run: docker push pd-chatbot:v0
