name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Define the branch where you want to trigger this workflow

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t pd-chatbot:v0 .

      - name: Push Docker image
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
          docker push pd-chatbot:v0
