name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths:
      - Dockerfile.dev  # Specify the path to your Dockerfile

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker buildx create --use
        docker buildx build -t python :latest -f Dockerfile.dev
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        docker push python :latest
