name: Sync Fork

on:
  schedule:
    - cron: "*/5 * * * *" # This schedule will run the workflow every 5 minutes
  workflow_run:
    workflows: ["bandit", "wapiti", "linter"]
    types:
      - completed
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Check if all checks passed
        id: checks
        run: echo ::set-output name=checks::true

      - name: Sync and merge upstream repository with your current repository
        if: steps.checks.outputs.checks == 'true'
        uses: dabreadman/sync-upstream-repo@v1.3.0
        with:
          upstream_repo: https://github.com/Khaanvani-Org/dev.git
          upstream_branch: main
          downstream_branch: main
          token: ${{ secrets.GITHUB_TOKEN }}
