name: Sync Dev to Test

on:
  schedule:
    - cron: '*/5 * * * *' # every 5 minutes
  workflow_run:
    workflows: ["bandit", "lintr"]
    types:
      - completed

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Check if previous workflows are successful
        run: |
          if [ "${{ github.event.workflow_run.conclusion }}" != "success" ]; then
            echo "One of the previous workflows failed, exiting."
            exit 1
          fi
      - name: Sync and merge upstream repository with the test repository
        uses: dabreadman/sync-upstream-repo@v1.3.0
        with:
          upstream_repo: https://github.com/Khaanvani-Org/dev.git
          upstream_branch: main
          downstream_repo: https://github.com/Khaanvani-Org/test.git
          downstream_branch: main
          token: ${{ secrets.GITHUB_TOKEN }}
