name: Push File

on:
  push:
    branches:
      - main

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Push a file to another repository
      uses: dmnemec/copy_file_to_another_repo_action@v1.1.1
      env:
       API_TOKEN_GITHUB: ${{ secrets.COPYREPO_KHAANVANI2 }} # Use the correct environment variable name
      with:
        source_file: 'try.py'
        destination_repo: 'Khaanvani-Org/test'
        user_email: 'eng21ct0039@dsu.edu.in'
        user_name: 's-sukriti'
        commit_message: 'A jj message for the commit'
