name: Push File & Security Scans

on:
  push:
    branches:
      - main

jobs:
  bandit_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Set Git identity
        run: |
          git config --global user.email "eng21ct0039@dsu.edu.in"
          git config --global user.name "Sukriti"
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Bandit
        run: |
          pip install bandit
          bandit -r .

  wapiti_scan:
    runs-on: ubuntu-latest
    needs: bandit_scan
    steps:
      - name: Install Wapiti
        run: |
          sudo apt-get -y install wapiti
          wapiti -u https://khaanvaani.streamlit.app/
      - name: Save Wapiti Scan Report
        uses: actions/upload-artifact@v2
        with:
          name: wapiti-scan-report
          path: /home/runner/.wapiti/generated_report

  copy-file:
    runs-on: ubuntu-latest
    needs: [bandit_scan, wapiti_scan]
    permissions:
      contents: write
      packages: write
      pages: write 
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: try.py
        uses: dmnemec/copy_file_to_another_repo_action@v1.1.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.PAT_TOKEN }} # Use the correct environment variable name
        with:
          source_file: 'try.py'
          destination_repo: 'Khaanvani-Org/test'
          user_email: 'eng21ct0039@dsu.edu.in'
          user_name: 's-sukriti'
        
      - name: readme.md
        uses: dmnemec/copy_file_to_another_repo_action@v1.1.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.PAT_TOKEN }} # Use the correct environment variable name
        with:
          source_file: 'README.md'
          destination_repo: 'Khaanvani-Org/test'
          user_email: 'eng21ct0039@dsu.edu.in'
          user_name: 's-sukriti'

      - name: src folder
        uses: dmnemec/copy_file_to_another_repo_action@v1.1.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.PAT_TOKEN }} # Use the correct environment variable name
        with:
          source_file: 'src/'
          destination_repo: 'Khaanvani-Org/test'
          user_email: 'eng21ct0039@dsu.edu.in'
          user_name: 's-sukriti'
