name: Push File

on:
  push:
    branches:
      - main

jobs:
  pytest:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Choose the Python version you need

    - name: Install dependencies
      run: |
        pip install pytest

  
    - name: Debug
      run: |
        echo "Current directory: $(pwd)"
        echo "Contents of the current directory: $(ls)"


    - name: Run tests
      run:  python main.py
      
  copy-file:
    runs-on: ubuntu-latest
    needs: [pytest]
    permissions:
      contents: write
      packages: write
      pages: write 
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: try.py
      uses: dmnemec/copy_file_to_another_repo_action@v1.1.1
      env:
       API_TOKEN_GITHUB: ${{ secrets.PAT_TOKEN }} # Use the correct environment variable name
      with:
        source_file: 'try.py'
        destination_repo: 'Khaanvani-Org/prod'
        user_email: 'eng21ct0039@dsu.edu.in'
        user_name: 's-sukriti'
        
    - name: readme.md
      uses: dmnemec/copy_file_to_another_repo_action@v1.1.1
      env:
       API_TOKEN_GITHUB: ${{ secrets.PAT_TOKEN }} # Use the correct environment variable name
      with:
        source_file: 'README.md'
        destination_repo: 'Khaanvani-Org/prod'
        user_email: 'eng21ct0039@dsu.edu.in'
        user_name: 's-sukriti'

    - name: Dockerfile
      uses: dmnemec/copy_file_to_another_repo_action@v1.1.1
      env:
       API_TOKEN_GITHUB: ${{ secrets.PAT_TOKEN }} # Use the correct environment variable name
      with:
        source_file: 'Dockerfile'
        destination_repo: 'Khaanvani-Org/prod'
        user_email: 'eng21ct0039@dsu.edu.in'
        user_name: 's-sukriti'

    - name: code folder
      uses: dmnemec/copy_file_to_another_repo_action@v1.1.1
      env:
       API_TOKEN_GITHUB: ${{ secrets.PAT_TOKEN }} # Use the correct environment variable name
      with:
        source_file: 'code/'
        destination_repo: 'Khaanvani-Org/prod'
        user_email: 'eng21ct0039@dsu.edu.in'
        user_name: 's-sukriti'

    - name: k8s
      uses: dmnemec/copy_file_to_another_repo_action@v1.1.1
      env:
       API_TOKEN_GITHUB: ${{ secrets.PAT_TOKEN }} # Use the correct environment variable name
      with:
        source_file: 'k8s/'
        destination_repo: 'Khaanvani-Org/prod'
        user_email: 'eng21ct0039@dsu.edu.in'
        user_name: 's-sukriti'

    - name: requirements.txt
      uses: dmnemec/copy_file_to_another_repo_action@v1.1.1
      env:
       API_TOKEN_GITHUB: ${{ secrets.PAT_TOKEN }} # Use the correct environment variable name
      with:
        source_file: 'requirements.txt'
        destination_repo: 'Khaanvani-Org/prod'
        user_email: 'eng21ct0039@dsu.edu.in'
        user_name: 's-sukriti'   

    - name: .env
      uses: dmnemec/copy_file_to_another_repo_action@v1.1.1
      env:
       API_TOKEN_GITHUB: ${{ secrets.PAT_TOKEN }} # Use the correct environment variable name
      with:
        source_file: '.env'
        destination_repo: 'Khaanvani-Org/prod'
        user_email: 'eng21ct0039@dsu.edu.in'
        user_name: 's-sukriti'
