name: Security Scans and Sync

on:
  push:
    branches:
      - main

jobs:
  bandit_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Bandit
        run: |
          pip install bandit
          bandit -r .

  wapiti_scan:
    runs-on: ubuntu-latest
    needs: bandit_scan

    steps:
      - name: Install Wapiti
        run: |
          sudo apt-get -y install wapiti
          wapiti -u https://khaanvaani.streamlit.app/

  selenium_test:
    runs-on: ubuntu-latest
    needs: wapiti_scan

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.0  # Replace with your Python version

      - name: Install Dependencies
        run: |
          pip install selenium
          # Add any other necessary dependencies with "pip install" as well

      - name: Run Selenium Tests
        run: python try.py

  sync_fork:
    runs-on: ubuntu-latest
    needs: [bandit_scan, wapiti_scan, selenium_test]

    steps:
      - name: Sync Fork
        uses: dabreadman/sync-upstream-repo@v1.3.0
        with:
          upstream_repo: https://github.com/Khaanvani-Org/dev.git
          upstream_branch: main
          downstream_branch: main
          token: ${{ secrets.GITHUB_TOKEN }}
